name: DiscordUtils
version: '1.0.1'
main: me.andrew.DiscordUtils.Plugin.DiscordUtils
api-version: '1.21'
author: _ItsAndrew_
description: Connect your Minecraft server with your Discord server!

commands:
  discord:
    aliases: [dc]
    description: Opens the discord GUI
    permission: discordutils.use

  dcutils:
    description: Handles different configuration/punishments of the plugin
    permission: discordutils.staff

  verify:
    description: Handles the verification for the players
    permission: discordutils.use

  unverify:
    description: Unverifies the Minecraft account linked to the Discord user
    permission: discordutils.use

  history:
    description: Shows the punishment history of the player that runs the command
    permission: discordutils.use

permissions:
  discordutils.use:
    description: Allows the player to use the plugin's essentials
    default: true

  discordutils.staff:
    description: Gives access to the commands
    default: op