name: DiscordUtils
version: '1.0.1'
main: me.andrew.DiscordUtils.Plugin.DiscordUtils
api-version: '1.21'
author: _ItsAndrew_

commands:
  discord:
    aliases: [dc]
    description: Opens the discord GUI
    permission: discordutils.use

  dcutils:
    description: Handles different configuration/punishments of the plugin
    permission: discordutils.staff

  verify:
    description: Handles the verification for the players
    permission: discordutils.use

  unverify:
    description: Unverifies the minecraft account linked to the discord user
    permission: discordutils.use

permissions:
  discordutils.use:
    description: Allows the use of the command
    default: true

  discordutils.staff:
    description: Gives access to the commands
    default: op