name: DiscordUtils
version: '1.0.1'
main: me.andrew.DiscordUtils.Plugin.DiscordUtils
api-version: '1.21'
author: _ItsAndrew_
description: Connect your Minecraft server with your Discord server!

commands:
  discord:
    aliases: [dc]
    description: Opens the discord GUI
    permission: discordutils.use

  dcutils:
    description: Handles different configuration/punishments of the plugin
    permission: discordutils.commands

  verify:
    description: Handles the verification for the players
    permission: discordutils.use

  unverify:
    description: Unverifies the Minecraft account linked to the Discord user
    permission: discordutils.use

  history:
    description: Shows the punishment history of the player that runs the command
    permission: discordutils.use

permissions:
  discordutils.use:
    description: Allows the players to use the plugin's essentials
    default: true

  discordutils.commands:
    description: Allows the player to use the plugin's commands
    default: op

  discordutils.commands.reload:
    description: Allows the player to run '/dcutils reload'
    default: op

  discordutils.commands.blockconfig:
    description: Allows the player to run '/dcutils blockconfig'
    default: op

  discordutils.commands.punishments:
    description: Gives access to the punishments command
    default: op

  discordutils.punishments.add:
    description: Gives access to add punishments
    default: op

  discordutils.punishments.remove:
    description: Gives access to remove punishments
    default: op

  discordutils.punishments.playerhistory:
    description: Gives access to see someone's history of punishments
    default: op